### ISSUE TITLE
计算loginkey失败

### ISSUE THREAD

**Issue by Eocil** [Pandaft/ESurfingPy-CLI#10]
计算loginkey失败
![image](https://user-images.githubusercontent.com/128161344/226525522-e98e4400-adac-46b1-b942-0f9637069349.png)

**Comment by Pandaft** [comment]
RSA 加密文本过长，最多只支持 117 个字符，但加密的文本却达到 119 个。

https://github.com/Pandaft/ESurfingPy-CLI/blob/131888f3f7f82c9ac62d6569c0b6fad3e714ccf8/esurfingpy/esurfing.py#L182-L186

RSA 加密的文本由 `账号` 、`密码` 和 `验证码` 组成，其中 `验证码` 固定长度为 4，所以是 `账号` 和 `密码` 的长度加起来太长所导致。尝试将修改密码，将长度减少 2 位或以上后，再使用程序登录试试。

**Comment by Pandaft** [comment]
找到了不用修改密码的解决方法，稍后修复并发布最新版。

**Comment by Pandaft** [comment]
已发布新版，试试看。

**Comment by Eocil** [comment]
成功了
