### ISSUE TITLE
Debian上无法运行

### ISSUE THREAD

**Issue by YipSzeho** [Pandaft/ESurfingPy-CLI#11]
二进制文件运行结果
![_QG7I` NN _Z29TSPZ 7OW](https://user-images.githubusercontent.com/58989046/227717605-0ffbf533-8fd3-4a07-99fb-43e47d99897a.png)

源码运行结果
![image](https://user-images.githubusercontent.com/58989046/227717703-e9aa30b4-0c85-44fd-9773-e943c00e836c.png)

**Comment by YipSzeho** [comment]
用源码跑起来了，需要apt install python3-tk

**Comment by Pandaft** [comment]
Python 在不同系统上存在差异，不同的 Linux 发行版需对应相同的系统构建才能正常运行。

而 GitHub Action 只提供 Ubuntu 系统，而其余系统则需要手动费时费力构建。

我没有时间和精力修复这个问题，因此这个问题不会修复，建议自行运行源码和构建。
